#!/bin/bash
n=`wc -l /etc/passwd | cut -d " " -f 1`
for i in `seq 1 "$n"`;
do
id=`sed -n "$i"p /etc/passwd | cut -d : -f 3`
if [ "$id" -eq 0 ] || [ "$id" -gt 500 ]; then
sed -n "$i"p /etc/passwd | cut -d : -f 1,3,4
fi
done

