#!/bin/bash
read -p "user :" user
n=`wc -l /etc/passwd | cut -d " " -f 1`
for i in `seq 1 "$n"`;
do
usera=`sed -n "$i"p /etc/passwd | cut -d : -f 1`
if [ "$usera" = "$user" ] 
then
	sed -n "$i"p /etc/passwd
fi 
done
