#!/bin/bash
clear
choix=0
echo "...........................GESTION LOGS................................."
while [ $choix -ne 1 -a $choix -ne 2 -a $choix -ne 3 -a $choix -ne 4 -a $choix -ne 5 ]
do
echo "              1- Pour editer le contenu de syslog.conf tapez 1"
echo "	   2- Pour créer des logs pour tout ce que fait votre script tapez 2"
echo "	   3- Pour effectuer une recherche dans les fichiers logs selon des 					critères entrés 3"
echo "		   4- Pour editer la configuration de logrotate selon les entrés 					de l'admin tapez 4"
echo "		    5- RETOUR 5"

echo "Donnez votre choix : "
echo -n
read choix
done
case $choix in
1) ./creer/creation;;
2) ./supp/supprimer;;
3) echo "vous avez choisi afff" ;;
4) echo "vous avez choisi mot" ;;
5) ./menu ;;
*) echo "valeur incorrecte" ;;
esac
