#!/bin/bash
clear
choix=0
echo "...........................GESTION RESEAU.................................."
while [ $choix -ne 1 -a $choix -ne 2 -a $choix -ne 3 -a $choix -ne 4 -a $choix -ne 5 -a $choix -ne 6 -a $choix -ne 7 ]
do
echo "                    1- Pour lister les cartes réseau et leur config tapez 1"
echo "		    2- Pour changer la configuration d'une carte tapez 2"
echo "		    3- Pour activer/desactiver une carte tapez 3"
echo "		    4- Pour changer de serveur de nomstapez 4"
echo "		    5- Pour changer le nom de la machine tapez 5"
echo "		    6- Pour redémarer le service réseau tapez 6"
echo "		    7- RETOUR 7"

echo "Donnez votre choix : "
echo -n
read choix
done
case $choix in
1) ./reseau/list/listerR;;
2) ./reseau/conf/confR;;
3) ./reseau/activer/actde;;
4) ./reseau/chser/ser;;
5) ./reseau/chnom/nom;;
6) ./reseau/red/redem;;
7) ./menu;;
*) echo "valeur incorrecte" ;;
esac
