#!/bin/bash
clear
choix=0
echo "...........................GESTION TACHES PLANIFIÉES.................................."
while [ $choix -ne 1 -a $choix -ne 2 -a $choix -ne 3 -a $choix -ne 4 -a $choix -ne 5 -a $choix -ne 6 ]
do
echo "                    1- Pour planifier une tache administrateur tapez 1"
echo "		    2- Pour planifier une tache simple utilisateur tapez 2"
echo "		    3- Pour planifier une tache AT tapez 3"
echo "		    4- Pour lister les tache planifiées tapez 4"
echo "		    5- Pour supprimer unr tache tapez 5"
echo "		    6- RETOUR 6"
echo "Donnez votre choix : "
echo -n
read choix
done
case $choix in
1) ./tache/admin;;
2) ./tache/s/simple;;
3) ./tache/AT ;;
4) ./tache/lister;;
5) ./tache/supp;;
6) ./menu;;
*) echo "valeur incorrecte" ;;
esac
