#!/bin/bash


echo "Donner le nom de la carte";  
read nom 

echo "1 pour activer 2 pour desactiver";

read choix 



if [ $choix = "1" ] ;

	then 
ifconfig eth0 up


elif [ $choix = "2" ] ;

	then 
ifconfig eth0 down

fi

